/**
 * Renowned nursing and midwifery training institutions in Ghana.
 * Used for the college/school selector in student registration and order forms.
 */

export const GHANA_NURSING_SCHOOLS: string[] = [
  // --- Public Nursing Training Colleges (Ministry of Health / Ghana Health Service) ---
  "Korle-Bu Nursing and Midwifery Training College",
  "Accra Nursing and Midwifery Training College",
  "Ada Nursing and Midwifery Training College",
  "Kpembe Nursing and Midwifery Training College",
  "Tamale Nursing and Midwifery Training College",
  "Bawku Nursing and Midwifery Training College",
  "Bogoso Nursing and Midwifery Training College",
  "Takoradi Nursing and Midwifery Training College",
  "Cape Coast Nursing and Midwifery Training College",
  "Kumasi Nursing and Midwifery Training College",
  "Holy Family Nursing and Midwifery Training College, Nkawkaw",
  "Effiduasi Nursing and Midwifery Training College",
  "Komfo Anokye Nursing and Midwifery Training College",
  "Sunyani Nursing and Midwifery Training College",
  "Bechem Nursing and Midwifery Training College",
  "Techiman Nursing and Midwifery Training College",
  "Wenchi Nursing and Midwifery Training College",
  "Ho Nursing and Midwifery Training College",
  "Hohoe Nursing and Midwifery Training College",
  "Keta Nursing and Midwifery Training College",
  "Koforidua Nursing and Midwifery Training College",
  "Akuse Nursing and Midwifery Training College",
  "Bolgatanga Nursing and Midwifery Training College",
  "Navrongo Nursing and Midwifery Training College",
  "Wa Nursing and Midwifery Training College",
  "Agona Swedru Nursing and Midwifery Training College",
  "Obuasi Nursing and Midwifery Training College",
  "Dunkwa Nursing and Midwifery Training College",
  "Teshie Nursing and Midwifery Training College",
  "Greater Accra Nursing and Midwifery Training College, Pantang",
  "Madina Nursing and Midwifery Training College",
  "Ashaiman Nursing and Midwifery Training College",
  "Jamestown Nursing and Midwifery Training College",
  "Axim Nursing and Midwifery Training College",
  "Saltpond Nursing and Midwifery Training College",
  "Mampong Nursing and Midwifery Training College",
  "Dormaa Ahenkuro Nursing and Midwifery Training College",
  "Jirapa Nursing and Midwifery Training College",
  "Navoro Nursing and Midwifery Training College",
  "Kpando Nursing and Midwifery Training College",
  "Sekondi Nursing and Midwifery Training College",
  "Tema Nursing and Midwifery Training College",
  "Ashaiman Nursing Training College",
  "Okaishie Nursing and Midwifery Training College",
  "Pig Farm Nursing and Midwifery Training College",

  // --- Universities with Nursing / Midwifery programmes ---
  "University of Ghana (BSc Nursing / Midwifery)",
  "Kwame Nkrumah University of Science and Technology (BSc Nursing)",
  "University of Cape Coast (BSc Nursing)",
  "University of Health and Allied Sciences (BSc Nursing / Midwifery)",
  "University for Development Studies (BSc Nursing)",
  "Catholic University College of Ghana (BSc Nursing)",
  "Presbyterian University College (BSc Nursing)",
  "Ghana Baptist University College (BSc Nursing)",
  "Valley View University (BSc Nursing)",
  "Central University (BSc Nursing)",
  "Christian Service University College (BSc Nursing)",
  "Anglican University College of Technology (BSc Nursing)",
  "BlueCrest University College (BSc Nursing)",
  "Ghana Technology University College (BSc Nursing)",
  "Wisconsin International University College (BSc Nursing)",
  "Regent University College of Science and Technology (BSc Nursing)",
  "Knutsford University College (BSc Nursing)",
  "University of Energy and Natural Resources (BSc Nursing)",
  "KNUST (Post-RN BSc Nursing)",

  // --- Other / private ---
  "Other",
];
