/**
 * Paystack inline payment helper.
 *
 * Loads the Paystack inline script once and exposes `payWithPaystack` to open
 * the payment popup. The caller passes a Paystack *reference* generated by
 * our backend (via /orders/:id/pay), and the popup collects the payment.
 * On success the caller verifies the reference server-side.
 */

const PAYSTACK_SCRIPT_URL = 'https://js.paystack.co/v2/inline.js';

let scriptLoaded = false;
let scriptPromise: Promise<void> | null = null;

/** Lazily inject the Paystack inline script once per page load. */
function loadScript(): Promise<void> {
  if (scriptLoaded) return Promise.resolve();
  if (scriptPromise) return scriptPromise;
  scriptPromise = new Promise<void>((resolve, reject) => {
    const existing = document.querySelector(`script[src="${PAYSTACK_SCRIPT_URL}"]`);
    if (existing) {
      scriptLoaded = true;
      resolve();
      return;
    }
    const script = document.createElement('script');
    script.src = PAYSTACK_SCRIPT_URL;
    script.async = true;
    script.onload = () => {
      scriptLoaded = true;
      resolve();
    };
    script.onerror = () => {
      scriptPromise = null;
      reject(new Error('Failed to load Paystack payment script.'));
    };
    document.head.appendChild(script);
  });
  return scriptPromise;
}

export type PaystackConfig = {
  /** Paystack public key (pk_test_... or pk_live_...). */
  key: string;
  /** The payment reference generated by our backend. */
  reference: string;
  /** Amount in GHS (lowest denomination — pesewas). 250 cedis = 25000. */
  amount: number;
  /** Customer email. */
  email: string;
  /** Currency code. */
  currency?: string;
  /** Human-readable label shown on the Paystack popup. */
  label?: string;
};

export type PaystackResult = {
  reference: string;
  status: string;
  trans: string;
  message: string;
};

/**
 * Open the Paystack inline payment popup.
 * Resolves with the transaction reference on success, rejects on close/failure.
 */
export async function payWithPaystack(config: PaystackConfig): Promise<PaystackResult> {
  await loadScript();

  return new Promise<PaystackResult>((resolve, reject) => {
    const handler = (window as unknown as Record<string, unknown>)['PaystackPop'] as {
      setup: (opts: Record<string, unknown>) => { openIframe: () => void };
    } | undefined;

    if (!handler) {
      reject(new Error('Paystack payment script did not load. Please try again.'));
      return;
    }

    const popup = handler.setup({
      key: config.key,
      ref: config.reference,
      amount: config.amount,
      email: config.email,
      currency: config.currency ?? 'GHS',
      label: config.label,
      onClose: () => {
        reject(new Error('Payment was cancelled.'));
      },
      callback: (response: PaystackResult) => {
        resolve(response);
      },
    });

    popup.openIframe();
  });
}

/**
 * Paystack publishable key from environment.
 * Set VITE_PAYSTACK_PUBLIC_KEY in your .env file.
 */
export function getPaystackKey(): string {
  const key = (import.meta.env.VITE_PAYSTACK_PUBLIC_KEY as string | undefined)?.trim();
  if (!key) {
    console.warn(
      'VITE_PAYSTACK_PUBLIC_KEY is not set — payments will fail. ' +
      'Add your Paystack public key to .env',
    );
  }
  return key ?? '';
}
