// Postgres schema for care study storage — mirrors ./index.ts (SQLite) so the
// same API and study data work against either backend. Used only when
// DB_DRIVER=postgres (e.g. when the app is deployed).

import {
  index,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const studiesTable = pgTable("studies", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  data: jsonb("data").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const studyVersionsTable = pgTable(
  "study_versions",
  {
    id: serial("id").primaryKey(),
    studyId: integer("study_id")
      .notNull()
      .references(() => studiesTable.id, { onDelete: "cascade" }),
    data: jsonb("data").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("study_versions_study_id_idx").on(table.studyId)],
);

export const studyFilesTable = pgTable(
  "study_files",
  {
    id: serial("id").primaryKey(),
    studyId: integer("study_id")
      .notNull()
      .references(() => studiesTable.id, { onDelete: "cascade" }),
    filename: text("filename").notNull(),
    storedPath: text("stored_path").notNull(),
    kind: text("kind").notNull().default("clinical"),
    mime: text("mime").notNull(),
    size: integer("size").notNull(),
    status: text("status").notNull().default("indexing"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("study_files_study_id_idx").on(table.studyId)],
);

export const librarySourcesTable = pgTable("library_sources", {
  id: serial("id").primaryKey(),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  author: text("author"),
  year: text("year"),
  venue: text("venue"),
  citeKey: text("cite_key"),
  url: text("url"),
  filename: text("filename").notNull(),
  storedPath: text("stored_path").notNull(),
  status: text("status").notNull().default("indexing"),
  error: text("error"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Studio admins — the only people who can open the studio / order bin
// (mirrors the SQLite schema in ./index.ts).
// ---------------------------------------------------------------------------
export const adminsTable = pgTable("admins", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  name: text("name"),
  /** "admin" (full access) or "staff" (studio + order bin only). */
  role: text("role").notNull().default("staff"),
  email: text("email"),
  invitedBy: integer("invited_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});


export const adminSessionsTable = pgTable("admin_sessions", {
  token: text("token").primaryKey(),
  adminId: integer("admin_id")
    .notNull()
    .references(() => adminsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Staff invite links — one-time registration tokens generated by admins. */
export const staffInvitesTable = pgTable("staff_invites", {
  id: serial("id").primaryKey(),
  token: text("token").notNull().unique(),
  createdBy: integer("created_by")
    .notNull()
    .references(() => adminsTable.id, { onDelete: "cascade" }),
  label: text("label"),
  usedAt: timestamp("used_at", { withTimezone: true }),
  usedBy: integer("used_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Student portal — accounts, sessions, and care-study orders (mirrors the
// SQLite schema in ./index.ts).
// ---------------------------------------------------------------------------

export const studentsTable = pgTable("students", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  username: text("username").notNull().unique(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  college: text("college").notNull(),
  program: text("program").notNull(),
  year: text("year"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const studentSessionsTable = pgTable("student_sessions", {
  token: text("token").primaryKey(),
  studentId: integer("student_id")
    .notNull()
    .references(() => studentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const studentOrdersTable = pgTable(
  "student_orders",
  {
    id: serial("id").primaryKey(),
    studentId: integer("student_id")
      .notNull()
      .references(() => studentsTable.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    diagnosis: text("diagnosis"),
    college: text("college").notNull(),
    program: text("program").notNull(),
    notes: text("notes"),
    correctionScope: text("correction_scope"),
    correctionText: text("correction_text"),
    status: text("status").notNull().default("submitted"),
    note: text("note"),
    producedStudyId: integer("produced_study_id"),
    deliveryFilename: text("delivery_filename"),
    deliveryPath: text("delivery_path"),
    deliverySize: integer("delivery_size"),
    /** Generated viva question bank (JSON) — cached on the order once produced. */
    vivaBank: text("viva_bank"),
    /** "none" | "pending" | "ready" | "error". */
    vivaStatus: text("viva_status").notNull().default("none"),
    vivaError: text("viva_error"),
    vivaUpdatedAt: timestamp("viva_updated_at", { withTimezone: true }),
    // --- Payment (Paystack) ---
    /** "none" | "pending" | "verified" | "failed". */
    paymentStatus: text("payment_status").notNull().default("none"),
    /** Which scope was paid for: "full" or "chapter". */
    paidScope: text("paid_scope"),
    /** Amount paid in Ghana cedis (e.g. 250.00). */
    paidAmount: integer("paid_amount"),
    /** Paystack transaction reference (unique). */
    paystackRef: text("paystack_ref"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("student_orders_student_id_idx").on(table.studentId)],
);

export const studentOrderFilesTable = pgTable(
  "student_order_files",
  {
    id: serial("id").primaryKey(),
    orderId: integer("order_id")
      .notNull()
      .references(() => studentOrdersTable.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    filename: text("filename").notNull(),
    storedPath: text("stored_path").notNull(),
    mime: text("mime").notNull(),
    size: integer("size").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("student_order_files_order_id_idx").on(table.orderId)],
);

export type Study = typeof studiesTable.$inferSelect;
export type InsertStudy = typeof studiesTable.$inferInsert;
export type StudyVersion = typeof studyVersionsTable.$inferSelect;
export type InsertStudyVersion = typeof studyVersionsTable.$inferInsert;
export type StudyFile = typeof studyFilesTable.$inferSelect;
export type InsertStudyFile = typeof studyFilesTable.$inferInsert;
export type LibrarySource = typeof librarySourcesTable.$inferSelect;
export type InsertLibrarySource = typeof librarySourcesTable.$inferInsert;
export type Student = typeof studentsTable.$inferSelect;
export type InsertStudent = typeof studentsTable.$inferInsert;
export type StudentSession = typeof studentSessionsTable.$inferSelect;
export type StudentOrder = typeof studentOrdersTable.$inferSelect;
export type InsertStudentOrder = typeof studentOrdersTable.$inferInsert;
export type StudentOrderFile = typeof studentOrderFilesTable.$inferSelect;
export type InsertStudentOrderFile = typeof studentOrderFilesTable.$inferInsert;
